#ifndef __PLAY_UTILITY_MESSAGE_TYPE_H__
#define __PLAY_UTILITY_MESSAGE_TYPE_H__


#define     PLAY_MESSAGE_VALUE_MAX      10000


// 基本的播放控制命令 //
typedef enum PlayCmd {
    PLAY_CMD_RESERVED = 0,
    PLAY_CMD_OPEN,
    PLAY_CMD_PLAY,
    PLAY_CMD_CLOSE,
    PLAY_CMD_PAUSE,
    PLAY_CMD_RESUME,        //5
    PLAY_CMD_STOP,
    PLAY_CMD_SEEKTO,
    PLAY_CMD_SEEKTO_START,
    PLAY_CMD_SEEKTO_END,
    PLAY_CMD_FASTFORWARD,   //10
    PLAY_CMD_FASTREWIND,
    PLAY_CMD_MAX
} PLAY_CMD;




// 基本的播放模式 //
typedef enum PlayMode {
    PLAY_MODE_RESERVED = 100,
    PLAY_MODE_PLAYFIRST,
    PLAY_MODE_PLAYLAST,
    PLAY_MODE_PLAYNEXT,
    PLAY_MODE_PLAYPREVIOUS,
    PLAY_MODE_PLAYREPEAT_LIST,      //5
    PLAY_MODE_PLAYREPEAT_ITEM,
    PLAY_MODE_PLAYONCE_BYLIST,
    PLAY_MODE_PLAYONCE_BYITEM,
    PLAY_MODE_PLAYSHUFFLE_BYLIST,
    PLAY_MODE_PLAYBYLISTINDEX,      //10
    PLAY_MODE_PLAYBYFILEOFFSET,
    PLAY_MODE_PLAYBYENTRYID,
    PLAY_MODE_MAX
} PLAY_MODE;

// 基本的播放列表操作 //
typedef enum PlayListCmd {
    PLAYLIST_CMD_RESERVED = 200,
    PLAYLIST_CMD_ADD_ITEMS,
    PLAYLIST_CMD_ADD_PLAYLIST,
    PLAYLIST_CMD_DELETE_ITEMS,      
    PLAYLIST_CMD_DELETE_PLAYLIST,
    PLAYLIST_CMD_SORTBY_FILENAME,    //5
    PLAYLIST_CMD_SORTBY_TIMELENGTH,       
    PLAYLIST_CMD_SORTBY_FILESIZE,
    PLAYLIST_CMD_SORTBY_FILETYPE,   
    PLAYLIST_CMD_MAX
} PLAYLIST_CMD;



// 用于获取播放信息的消息 //
typedef enum PlayMessage{
    PLAY_MESSAGE_RESERVED = 1000,
    PLAY_MESSAGE_1,
    PLAY_MESSAGE_2,
    PLAY_MESSAGE_3,
    PLAY_MESSAGE_4,
    PLAY_MESSAGE_5,     //5
    PLAY_MESSAGE_6,
    PLAY_MESSAGE_7,
    PLAY_MESSAGE_8,
    PLAY_MESSAGE_9,
    PLAY_MESSAGE_MAX
} PLAY_MESSAGE;


typedef struct PlayerCommand{
    int cmd; /* type: PLAY_CMD or PLAY_MODE or PLAY_MESSAGE */
    int subCMD;
    int arg1;
    int arg2;
} PlayerCommand_Type;














#endif  //__PLAY_UTILITY_MESSAGE_TYPE_H__

